server:
  port: 8001

spring:
  application:
    name:  cloud-paymet-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.128.101:3306/cloud2020?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Pwd@123456

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: org.springcloud.entity