server:
  port: 9527

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - uri: lb://cloud-paymet-service
          predicates:
            - Path=/payment/get/**
            - After=2020-07-26T13:43:44.411505+08:00[Asia/Shanghai]
            - Cookie=role, svip
            - Method=GET
        - id: payment_route2
          uri: lb://cloud-paymet-service
          predicates:
            - Path=/payment/create/**
#        - id: guonei
#          uri: http://news.baidu.com/
#          predicates:
#            - Path=/guonei

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}