server:
  port: 7001

eureka:
  instance:
    prefer-ip-address: true
    instance-id:
  client:
    fetch-registry: false #表示自己是注册中心，不需要检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: true