server:
  port: 7001

spring:
  application:
    name: eureka-replica1

eureka:
  instance:
    hostname: 127.0.0.1
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka/
