server:
  port: 7001

spring:
  application:
    name: eureka-server # Eureka集群的applicationName必须一致，不然集群模式起不来

eureka:
  instance:
    hostname: eureka1.com #默认用的是hostName 不能用一样的，如果在同一台机器上，可以改host
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/
