server:
  port: 7002

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka2.com
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka1.com:7001/eureka/,http://eureka3.com:7003/eureka/
